services:
  mysql:
    image: mysql:8
    container_name: domusiot-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - domus_net 

  mosquitto:
    image: eclipse-mosquitto
    container_name: domusiot-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto

  backend:
    build:
      context: ../backend
    container_name: domusiot-backend
    depends_on:
      - mysql
      - mosquitto
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - domus_net

volumes:
 mysql_data:

networks:
 domus_net:

